/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_josephmoscoso;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author joseph
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jd_mundod = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_nombretor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_pesotor = new javax.swing.JTextField();
        jb_agregartt = new javax.swing.JButton();
        jd_criatura = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_raza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_numeroe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_edadm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_region = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtf_cantv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtf_pesoc = new javax.swing.JTextField();
        criaturaagregar = new javax.swing.JButton();
        menupop = new javax.swing.JPopupMenu();
        m_modificar = new javax.swing.JMenuItem();
        m_eliminar = new javax.swing.JMenuItem();
        poparbol = new javax.swing.JPopupMenu();
        t_modificar = new javax.swing.JMenuItem();
        t_eliminar = new javax.swing.JMenuItem();
        jd_universo = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_codigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf_edadu = new javax.swing.JTextField();
        agregar_u = new javax.swing.JButton();
        popupmun = new javax.swing.JPopupMenu();
        mm_modificar = new javax.swing.JMenuItem();
        mm_eliminar = new javax.swing.JMenuItem();
        jd_modificarcriatura = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        raza = new javax.swing.JButton();
        energia = new javax.swing.JButton();
        años = new javax.swing.JButton();
        region = new javax.swing.JButton();
        vivas = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_mundodisco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_mundodisco = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_criatura = new javax.swing.JList<>();
        jb_converm = new javax.swing.JButton();
        jb_converc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_universo = new javax.swing.JTree();
        jb_universo = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("Agregar Mundo Disco");

        jLabel3.setText("Nombre de la tortuga");

        jLabel4.setText("Peso de la tortuga");

        jb_agregartt.setText("Agregar");
        jb_agregartt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarttMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_mundodLayout = new javax.swing.GroupLayout(jd_mundod.getContentPane());
        jd_mundod.getContentPane().setLayout(jd_mundodLayout);
        jd_mundodLayout.setHorizontalGroup(
            jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mundodLayout.createSequentialGroup()
                .addGroup(jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mundodLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2))
                    .addGroup(jd_mundodLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_nombretor, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mundodLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_pesotor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mundodLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jb_agregartt)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jd_mundodLayout.setVerticalGroup(
            jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mundodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_nombretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_pesotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jb_agregartt)
                .addGap(47, 47, 47))
        );

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setText("Agregar Criatura");

        jLabel6.setText("Raza");

        jLabel7.setText("Numero de eneregia");

        jLabel8.setText("Numero maximo de edad");

        jLabel9.setText("Nombre de la region");

        jLabel10.setText("Cantidad viva de criaturas");

        jLabel11.setText("Peso criaturas");

        criaturaagregar.setText("Agregar");
        criaturaagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criaturaagregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_criaturaLayout = new javax.swing.GroupLayout(jd_criatura.getContentPane());
        jd_criatura.getContentPane().setLayout(jd_criaturaLayout);
        jd_criaturaLayout.setHorizontalGroup(
            jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_numeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_criaturaLayout.createSequentialGroup()
                        .addComponent(jtf_edadm, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_criaturaLayout.createSequentialGroup()
                        .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_region)
                            .addGroup(jd_criaturaLayout.createSequentialGroup()
                                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_cantv, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(jtf_pesoc))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_criaturaLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(criaturaagregar))
                    .addGroup(jd_criaturaLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_criaturaLayout.setVerticalGroup(
            jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_numeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtf_edadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jtf_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtf_cantv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_pesoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(criaturaagregar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        m_modificar.setText("Modificar");
        m_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_modificarActionPerformed(evt);
            }
        });
        menupop.add(m_modificar);

        m_eliminar.setText("Eliminar");
        m_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_eliminarActionPerformed(evt);
            }
        });
        menupop.add(m_eliminar);

        t_modificar.setText("Modificar");
        poparbol.add(t_modificar);

        t_eliminar.setText("Eliminar");
        poparbol.add(t_eliminar);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setText("Crear Universo");

        jLabel13.setText("Codigo del universo");

        jLabel14.setText("Edad del universo");

        agregar_u.setText("Agregar Universo");
        agregar_u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_uMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_universoLayout = new javax.swing.GroupLayout(jd_universo.getContentPane());
        jd_universo.getContentPane().setLayout(jd_universoLayout);
        jd_universoLayout.setHorizontalGroup(
            jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_universoLayout.createSequentialGroup()
                .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_universoLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel12))
                    .addGroup(jd_universoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_edadu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_universoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregar_u)
                .addGap(155, 155, 155))
        );
        jd_universoLayout.setVerticalGroup(
            jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_universoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtf_edadu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregar_u)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mm_modificar.setText("Modificar");
        mm_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mm_modificarActionPerformed(evt);
            }
        });
        popupmun.add(mm_modificar);

        mm_eliminar.setText("Eliminar");
        mm_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mm_eliminarActionPerformed(evt);
            }
        });
        popupmun.add(mm_eliminar);

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel15.setText("Presione un boton para editar");

        raza.setText("Raza");
        raza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                razaMouseClicked(evt);
            }
        });

        energia.setText("Numero de energia");
        energia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                energiaMouseClicked(evt);
            }
        });

        años.setText("Numero maximo de años");
        años.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añosMouseClicked(evt);
            }
        });

        region.setText("Nombre de la region");
        region.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regionMouseClicked(evt);
            }
        });

        vivas.setText("Cantidad de especies vivas");
        vivas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vivasMouseClicked(evt);
            }
        });

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarcriaturaLayout = new javax.swing.GroupLayout(jd_modificarcriatura.getContentPane());
        jd_modificarcriatura.getContentPane().setLayout(jd_modificarcriaturaLayout);
        jd_modificarcriaturaLayout.setHorizontalGroup(
            jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel15))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(raza, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(energia))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(region))
                            .addComponent(años))))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarcriaturaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(vivas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_modificarcriaturaLayout.setVerticalGroup(
            jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(raza)
                .addGap(18, 18, 18)
                .addComponent(energia)
                .addGap(18, 18, 18)
                .addComponent(años)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(region)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vivas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Registro criaturas");

        jb_mundodisco.setText("Agregar Mundo Disco");
        jb_mundodisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_mundodiscoMouseClicked(evt);
            }
        });

        jl_mundodisco.setModel(new DefaultListModel());
        jl_mundodisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_mundodiscoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_mundodisco);

        jButton1.setText("Agregar criatura");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jl_criatura.setModel(new DefaultListModel());
        jl_criatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_criaturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_criatura);

        jb_converm.setText("------>");
        jb_converm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_convermMouseClicked(evt);
            }
        });

        jb_converc.setText("------>");
        jb_converc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_convercMouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Universo");
        jt_universo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_universo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_universoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_universo);

        jb_universo.setText("Agregar Universo");
        jb_universo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_universoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jb_mundodisco, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_converm)
                                    .addComponent(jb_converc))
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_universo)
                                .addGap(64, 64, 64)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_mundodisco)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jb_converm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_converc)
                        .addGap(166, 166, 166))))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jb_universo)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_mundodiscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_mundodiscoMouseClicked
        // TODO add your handling code here:
        jd_mundod.setModal(true);
        jd_mundod.pack();
        jd_mundod.setLocationRelativeTo(this);
        jd_mundod.setVisible(true);
    }//GEN-LAST:event_jb_mundodiscoMouseClicked

    private void jb_agregarttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarttMouseClicked
        // TODO add your handling code here:
        try {
            String nombre = jtf_nombretor.getText();
            int peso = Integer.parseInt(jtf_pesotor.getText());
            DefaultListModel modelo = (DefaultListModel) jl_mundodisco.getModel();
            modelo.addElement(new mundod(nombre, peso));
            jl_mundodisco.setModel(modelo);
            jtf_nombretor.setText("");
            jtf_pesotor.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_mundod, "Error, dato mal ingresado");
        }

    }//GEN-LAST:event_jb_agregarttMouseClicked

    private void criaturaagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criaturaagregarMouseClicked
        // TODO add your handling code here:
        try {
            String raza = jtf_raza.getText();
            int energia = Integer.parseInt(jtf_numeroe.getText());
            int edad = Integer.parseInt(jtf_edadm.getText());
            String region = jtf_region.getText();
            int viva = Integer.parseInt(jtf_cantv.getText());
            int peso = Integer.parseInt(jtf_pesoc.getText());
            DefaultListModel modelo2 = (DefaultListModel) jl_criatura.getModel();
            modelo2.addElement(new criaturas(raza, energia, edad, region, viva, peso));
            jl_criatura.setModel(modelo2);
            jtf_raza.setText("");
            jtf_numeroe.setText("");
            jtf_edadm.setText("");
            jtf_region.setText("");
            jtf_cantv.setText("");
            jtf_pesoc.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_criatura, "Error, dato mal ingresado");
        }
    }//GEN-LAST:event_criaturaagregarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_criatura.setModal(true);
        jd_criatura.pack();
        jd_criatura.setLocationRelativeTo(this);
        jd_criatura.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_universoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_universoMouseClicked
        // TODO add your handling code here:
        if (jb_universo.isEnabled()) {
            jd_universo.setModal(true);
            jd_universo.pack();
            jd_universo.setLocationRelativeTo(this);
            jd_universo.setVisible(true);
        }/*else{
            JOptionPane.showMessageDialog(this, "Error, ya hay un universo creado");
        }*/

    }//GEN-LAST:event_jb_universoMouseClicked

    private void agregar_uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_uMouseClicked
        // TODO add your handling code here:
        String codigo = jtf_codigo.getText();
        int edad = Integer.parseInt(jtf_edadu.getText());
        DefaultTreeModel m = (DefaultTreeModel) jt_universo.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(new universo(codigo, edad, 0));
        raiz.add(nodo);
        m.reload();
        jb_universo.setEnabled(false);
        jd_universo.setVisible(false);
    }//GEN-LAST:event_agregar_uMouseClicked

    private void jl_mundodiscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_mundodiscoMouseClicked
        if (evt.isMetaDown()) {
            if (jl_mundodisco.getSelectedIndex() >= 0) {
                popupmun.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_mundodiscoMouseClicked

    private void jl_criaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_criaturaMouseClicked
        if (evt.isMetaDown()) {
            if (jl_criatura.getSelectedIndex() >= 0) {
                menupop.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_criaturaMouseClicked

    private void jt_universoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_universoMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            poparbol.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jt_universoMouseClicked

    private void mm_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mm_modificarActionPerformed
        // TODO add your handling code here:
        String nombre = "";
        if (jl_mundodisco.getSelectedIndex() >= 0) {
            try {
                nombre = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error, dato incorrecto");
            }
            DefaultListModel modelo = (DefaultListModel) jl_mundodisco.getModel();
            String nac = ((mundod) modelo.get(jl_mundodisco.getSelectedIndex())).getNombre();
            int peso = ((mundod) modelo.get(jl_mundodisco.getSelectedIndex())).getPesot();
            mundod x = new mundod(nombre, peso);
            int c = jl_mundodisco.getSelectedIndex();
            modelo.setElementAt(x, c);
            jl_mundodisco.setModel(modelo);
            jtf_nombretor.setText("");
            jtf_pesotor.setText("");
        }

    }//GEN-LAST:event_mm_modificarActionPerformed

    private void mm_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mm_eliminarActionPerformed
        // TODO add your handling code here:
        if (jl_mundodisco.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_mundodisco.getModel();
            int c = jl_mundodisco.getSelectedIndex();
            modelo.remove(jl_mundodisco.getSelectedIndex());
        }
    }//GEN-LAST:event_mm_eliminarActionPerformed

    private void m_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_modificarActionPerformed
        // TODO add your handling code here:
        if (jl_criatura.getSelectedIndex() >= 0) {
            jd_modificarcriatura.setModal(true);
            jd_modificarcriatura.pack();
            jd_modificarcriatura.setLocationRelativeTo(this);
            jd_modificarcriatura.setVisible(true);
        }
    }//GEN-LAST:event_m_modificarActionPerformed

    private void m_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_eliminarActionPerformed
        // TODO add your handling code here:
        if (jl_criatura.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_criatura.getModel();
            int c = jl_criatura.getSelectedIndex();
            modelo.remove(jl_criatura.getSelectedIndex());
        }
    }//GEN-LAST:event_m_eliminarActionPerformed

    private void razaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_razaMouseClicked
        // TODO add your handling code here:
        String nombre = "";
        //if (jl_mundodisco.getSelectedIndex() >= 0) {
        try {
            nombre = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre de la raza");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error, dato incorrecto");
        }
        DefaultListModel modelo = (DefaultListModel) jl_criatura.getModel();
        int numero = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getNumero();
        int años = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getAños();
        String nac = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getRegion();
        int cantidad = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getCantidad();
        int peso = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getPesoc();
        criaturas x = new criaturas(nombre, numero, años, nac, cantidad, peso);
        int c = jl_criatura.getSelectedIndex();
        modelo.setElementAt(x, c);
        jl_criatura.setModel(modelo);
        jtf_raza.setText("");
        jtf_numeroe.setText("");
        jtf_edadm.setText("");
        jtf_region.setText("");
        jtf_cantv.setText("");
        jtf_pesoc.setText("");
        // }
    }//GEN-LAST:event_razaMouseClicked

    private void energiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_energiaMouseClicked
        // TODO add your handling code here:
        int nombre = 0;
        //if (jl_mundodisco.getSelectedIndex() >= 0) {
        try {
            nombre = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la nueva energia"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error, dato incorrecto");
        }
        DefaultListModel modelo = (DefaultListModel) jl_criatura.getModel();
        String numero = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getRaza();
        int años = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getAños();
        String nac = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getRegion();
        int cantidad = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getCantidad();
        int peso = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getPesoc();
        criaturas x = new criaturas(numero, nombre, años, nac, cantidad, peso);
        int c = jl_criatura.getSelectedIndex();
        modelo.setElementAt(x, c);
        jl_criatura.setModel(modelo);
        jtf_raza.setText("");
        jtf_numeroe.setText("");
        jtf_edadm.setText("");
        jtf_region.setText("");
        jtf_cantv.setText("");
        jtf_pesoc.setText("");
        //}
    }//GEN-LAST:event_energiaMouseClicked

    private void añosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añosMouseClicked
        // TODO add your handling code here:
        int nombre = 0;
        //if (jl_mundodisco.getSelectedIndex() >= 0) {
        try {
            nombre = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el nuevo año"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error, dato incorrecto");
        }
        DefaultListModel modelo = (DefaultListModel) jl_criatura.getModel();
        String numero = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getRaza();
        int años = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getNumero();
        String nac = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getRegion();
        int cantidad = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getCantidad();
        int peso = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getPesoc();
        criaturas x = new criaturas(numero, años, nombre, nac, cantidad, peso);
        int c = jl_criatura.getSelectedIndex();
        modelo.setElementAt(x, c);
        jl_criatura.setModel(modelo);
        jtf_raza.setText("");
        jtf_numeroe.setText("");
        jtf_edadm.setText("");
        jtf_region.setText("");
        jtf_cantv.setText("");
        jtf_pesoc.setText("");
        // }
    }//GEN-LAST:event_añosMouseClicked

    private void regionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regionMouseClicked
        // TODO add your handling code here:
        String nombre = "";
        //if (jl_mundodisco.getSelectedIndex() >= 0) {
        try {
            nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre de la region");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error, dato incorrecto");
        }
        DefaultListModel modelo = (DefaultListModel) jl_criatura.getModel();

        int numero = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getNumero();
        int años = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getAños();
        String nac = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getRaza();
        int cantidad = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getCantidad();
        int peso = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getPesoc();
        criaturas x = new criaturas(nac, numero, años, nombre, cantidad, peso);
        int c = jl_criatura.getSelectedIndex();
        modelo.setElementAt(x, c);
        jl_criatura.setModel(modelo);
        jtf_raza.setText("");
        jtf_numeroe.setText("");
        jtf_edadm.setText("");
        jtf_region.setText("");
        jtf_cantv.setText("");
        jtf_pesoc.setText("");
        //}
    }//GEN-LAST:event_regionMouseClicked

    private void vivasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vivasMouseClicked
        // TODO add your handling code here:
        int nombre = 0;
        //if (jl_mundodisco.getSelectedIndex() >= 0) {
        try {
            nombre = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la cantidad de especies vivas"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error, dato incorrecto");
        }
        DefaultListModel modelo = (DefaultListModel) jl_criatura.getModel();
        String numero = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getRaza();
        int años = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getNumero();
        String nac = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getRegion();
        int cantidad = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getAños();
        int peso = ((criaturas) modelo.get(jl_criatura.getSelectedIndex())).getPesoc();
        criaturas x = new criaturas(numero, años, cantidad, nac, nombre, peso);
        int c = jl_criatura.getSelectedIndex();
        modelo.setElementAt(x, c);
        jl_criatura.setModel(modelo);
        jtf_raza.setText("");
        jtf_numeroe.setText("");
        jtf_edadm.setText("");
        jtf_region.setText("");
        jtf_cantv.setText("");
        jtf_pesoc.setText("");
        //}
    }//GEN-LAST:event_vivasMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        jd_modificarcriatura.setVisible(false);
    }//GEN-LAST:event_salirMouseClicked

    private void jb_convermMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_convermMouseClicked
        // TODO add your handling code here:
        if (jl_mundodisco.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_universo.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            DefaultListModel modeloLista = (DefaultListModel) jl_mundodisco.getModel();
            String nacionalidad, nombre;
            int edad;
      //      nacionalidad = ((persona) modeloLista.get(jl_personas.getSelectedIndex())).getNacionalidad();
            nombre = ((mundod) modeloLista.get(jl_mundodisco.getSelectedIndex())).getNombre();
            edad = ((mundod) modeloLista.get(jl_mundodisco.getSelectedIndex())).getPesot();
            int centinela = -1;
            DefaultMutableTreeNode p = new DefaultMutableTreeNode(new mundod(nombre, edad));
            raiz.add(p);
            modeloARBOL.reload();
        } else {
            JOptionPane.showMessageDialog(this, "No hay personas seleccionadas");
        }
    }//GEN-LAST:event_jb_convermMouseClicked

    private void jb_convercMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_convercMouseClicked
        // TODO add your handling code here:
        if (jl_criatura.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_universo.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            DefaultListModel modeloLista = (DefaultListModel) jl_criatura.getModel();
            int posicion=Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la posicion del mundo"));
            String raza, reg;
            int energ, maximo, cant;
            int pes;
            raza = ((criaturas) modeloLista.get(jl_criatura.getSelectedIndex())).getRaza();
            pes = ((criaturas) modeloLista.get(jl_criatura.getSelectedIndex())).getPesoc();
            reg = ((criaturas) modeloLista.get(jl_criatura.getSelectedIndex())).getRegion();
            energ = ((criaturas) modeloLista.get(jl_criatura.getSelectedIndex())).getNumero();
            maximo = ((criaturas) modeloLista.get(jl_criatura.getSelectedIndex())).getAños();
            cant = ((criaturas) modeloLista.get(jl_criatura.getSelectedIndex())).getCantidad();
            DefaultMutableTreeNode p =new DefaultMutableTreeNode (new criaturas(raza, energ, maximo, reg, cant, pes));
            ((DefaultMutableTreeNode)raiz.getChildAt(posicion)).add(p);
            modeloARBOL.reload();
        } else {
            JOptionPane.showMessageDialog(this, "No hay personas seleccionadas");
        }
    }//GEN-LAST:event_jb_convercMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_u;
    private javax.swing.JButton años;
    private javax.swing.JButton criaturaagregar;
    private javax.swing.JButton energia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_agregartt;
    private javax.swing.JButton jb_converc;
    private javax.swing.JButton jb_converm;
    private javax.swing.JButton jb_mundodisco;
    private javax.swing.JButton jb_universo;
    private javax.swing.JDialog jd_criatura;
    private javax.swing.JDialog jd_modificarcriatura;
    private javax.swing.JDialog jd_mundod;
    private javax.swing.JDialog jd_universo;
    private javax.swing.JList<String> jl_criatura;
    private javax.swing.JList<String> jl_mundodisco;
    private javax.swing.JTree jt_universo;
    private javax.swing.JTextField jtf_cantv;
    private javax.swing.JTextField jtf_codigo;
    private javax.swing.JTextField jtf_edadm;
    private javax.swing.JTextField jtf_edadu;
    private javax.swing.JTextField jtf_nombretor;
    private javax.swing.JTextField jtf_numeroe;
    private javax.swing.JTextField jtf_pesoc;
    private javax.swing.JTextField jtf_pesotor;
    private javax.swing.JTextField jtf_raza;
    private javax.swing.JTextField jtf_region;
    private javax.swing.JMenuItem m_eliminar;
    private javax.swing.JMenuItem m_modificar;
    private javax.swing.JPopupMenu menupop;
    private javax.swing.JMenuItem mm_eliminar;
    private javax.swing.JMenuItem mm_modificar;
    private javax.swing.JPopupMenu poparbol;
    private javax.swing.JPopupMenu popupmun;
    private javax.swing.JButton raza;
    private javax.swing.JButton region;
    private javax.swing.JButton salir;
    private javax.swing.JMenuItem t_eliminar;
    private javax.swing.JMenuItem t_modificar;
    private javax.swing.JButton vivas;
    // End of variables declaration//GEN-END:variables
}
