/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_josephmoscoso;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author joseph
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jd_mundod = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_nombretor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_pesotor = new javax.swing.JTextField();
        jb_agregartt = new javax.swing.JButton();
        jd_criatura = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_raza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_numeroe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_edadm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_region = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtf_cantv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtf_pesoc = new javax.swing.JTextField();
        criaturaagregar = new javax.swing.JButton();
        menupop = new javax.swing.JPopupMenu();
        m_modificar = new javax.swing.JMenuItem();
        m_eliminar = new javax.swing.JMenuItem();
        poparbol = new javax.swing.JPopupMenu();
        t_modificar = new javax.swing.JMenuItem();
        t_eliminar = new javax.swing.JMenuItem();
        jd_universo = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_codigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf_edadu = new javax.swing.JTextField();
        agregar_u = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_mundodisco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_mundodisco = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_criatura = new javax.swing.JList<>();
        jb_converm = new javax.swing.JButton();
        jb_converc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_universo = new javax.swing.JTree();
        jb_universo = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("Agregar Mundo Disco");

        jLabel3.setText("Nombre de la tortuga");

        jLabel4.setText("Peso de la tortuga");

        jb_agregartt.setText("Agregar");
        jb_agregartt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarttMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_mundodLayout = new javax.swing.GroupLayout(jd_mundod.getContentPane());
        jd_mundod.getContentPane().setLayout(jd_mundodLayout);
        jd_mundodLayout.setHorizontalGroup(
            jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mundodLayout.createSequentialGroup()
                .addGroup(jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mundodLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2))
                    .addGroup(jd_mundodLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_nombretor, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mundodLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_pesotor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mundodLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jb_agregartt)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jd_mundodLayout.setVerticalGroup(
            jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mundodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_nombretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_mundodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_pesotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jb_agregartt)
                .addGap(47, 47, 47))
        );

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setText("Agregar Criatura");

        jLabel6.setText("Raza");

        jLabel7.setText("Numero de eneregia");

        jLabel8.setText("Numero maximo de edad");

        jLabel9.setText("Nombre de la region");

        jLabel10.setText("Cantidad viva de criaturas");

        jLabel11.setText("Peso criaturas");

        criaturaagregar.setText("Agregar");
        criaturaagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criaturaagregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_criaturaLayout = new javax.swing.GroupLayout(jd_criatura.getContentPane());
        jd_criatura.getContentPane().setLayout(jd_criaturaLayout);
        jd_criaturaLayout.setHorizontalGroup(
            jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_numeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_criaturaLayout.createSequentialGroup()
                        .addComponent(jtf_edadm, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_criaturaLayout.createSequentialGroup()
                        .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_region)
                            .addGroup(jd_criaturaLayout.createSequentialGroup()
                                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_cantv, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(jtf_pesoc))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_criaturaLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(criaturaagregar))
                    .addGroup(jd_criaturaLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_criaturaLayout.setVerticalGroup(
            jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_numeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtf_edadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jtf_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtf_cantv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_pesoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(criaturaagregar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        m_modificar.setText("Modificar");
        menupop.add(m_modificar);

        m_eliminar.setText("Eliminar");
        menupop.add(m_eliminar);

        t_modificar.setText("Modificar");
        poparbol.add(t_modificar);

        t_eliminar.setText("Eliminar");
        poparbol.add(t_eliminar);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setText("Crear Universo");

        jLabel13.setText("Codigo del universo");

        jLabel14.setText("Edad del universo");

        agregar_u.setText("Agregar Universo");
        agregar_u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_uMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_universoLayout = new javax.swing.GroupLayout(jd_universo.getContentPane());
        jd_universo.getContentPane().setLayout(jd_universoLayout);
        jd_universoLayout.setHorizontalGroup(
            jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_universoLayout.createSequentialGroup()
                .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_universoLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel12))
                    .addGroup(jd_universoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_edadu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_universoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregar_u)
                .addGap(155, 155, 155))
        );
        jd_universoLayout.setVerticalGroup(
            jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_universoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtf_edadu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregar_u)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Registro criaturas");

        jb_mundodisco.setText("Agregar Mundo Disco");
        jb_mundodisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_mundodiscoMouseClicked(evt);
            }
        });

        jl_mundodisco.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_mundodisco);

        jButton1.setText("Agregar criatura");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jl_criatura.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_criatura);

        jb_converm.setText("------>");

        jb_converc.setText("------>");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Universo");
        jt_universo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_universo);

        jb_universo.setText("Agregar Universo");
        jb_universo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_universoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jb_mundodisco, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_converm)
                                    .addComponent(jb_converc))
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_universo)
                                .addGap(64, 64, 64)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_mundodisco)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jb_converm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_converc)
                        .addGap(166, 166, 166))))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jb_universo)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_mundodiscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_mundodiscoMouseClicked
        // TODO add your handling code here:
        jd_mundod.setModal(true);
        jd_mundod.pack();
        jd_mundod.setLocationRelativeTo(this);
        jd_mundod.setVisible(true);
    }//GEN-LAST:event_jb_mundodiscoMouseClicked

    private void jb_agregarttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarttMouseClicked
        // TODO add your handling code here:
        try {
            String nombre = jtf_nombretor.getText();
            int peso = Integer.parseInt(jtf_pesotor.getText());
            DefaultListModel modelo = (DefaultListModel) jl_mundodisco.getModel();
            modelo.addElement(new mundod(nombre, peso));
            jl_mundodisco.setModel(modelo);
            jtf_nombretor.setText("");
            jtf_pesotor.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_mundod, "Error, dato mal ingresado");
        }

    }//GEN-LAST:event_jb_agregarttMouseClicked

    private void criaturaagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criaturaagregarMouseClicked
        // TODO add your handling code here:
        try {
            String raza = jtf_raza.getText();
            int energia = Integer.parseInt(jtf_numeroe.getText());
            int edad = Integer.parseInt(jtf_edadm.getText());
            String region = jtf_region.getText();
            int viva = Integer.parseInt(jtf_cantv.getText());
            int peso = Integer.parseInt(jtf_pesoc.getText());
            DefaultListModel modelo2 = (DefaultListModel) jl_criatura.getModel();
            modelo2.addElement(new criaturas(raza, energia, edad, region, viva, peso));
            jl_criatura.setModel(modelo2);
            jtf_raza.setText("");
            jtf_numeroe.setText("");
            jtf_edadm.setText("");
            jtf_region.setText("");
            jtf_cantv.setText("");
            jtf_pesoc.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_criatura, "Error, dato mal ingresado");
        }
    }//GEN-LAST:event_criaturaagregarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_criatura.setModal(true);
        jd_criatura.pack();
        jd_criatura.setLocationRelativeTo(this);
        jd_criatura.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_universoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_universoMouseClicked
        // TODO add your handling code here:
        if (jb_universo.isEnabled()) {
            jd_universo.setModal(true);
            jd_universo.pack();
            jd_universo.setLocationRelativeTo(this);
            jd_universo.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Error, ya hay un universo creado");
        }
        
    }//GEN-LAST:event_jb_universoMouseClicked

    private void agregar_uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_uMouseClicked
        // TODO add your handling code here:
        String codigo = jtf_codigo.getText();
        int edad = Integer.parseInt(jtf_edadu.getText());
        DefaultTreeModel m = (DefaultTreeModel) jt_universo.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(new universo(codigo, edad, 0));
        raiz.add(nodo);
        m.reload();
        jb_universo.setEnabled(false);
        jd_universo.setVisible(false);
    }//GEN-LAST:event_agregar_uMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_u;
    private javax.swing.JButton criaturaagregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_agregartt;
    private javax.swing.JButton jb_converc;
    private javax.swing.JButton jb_converm;
    private javax.swing.JButton jb_mundodisco;
    private javax.swing.JButton jb_universo;
    private javax.swing.JDialog jd_criatura;
    private javax.swing.JDialog jd_mundod;
    private javax.swing.JDialog jd_universo;
    private javax.swing.JList<String> jl_criatura;
    private javax.swing.JList<String> jl_mundodisco;
    private javax.swing.JTree jt_universo;
    private javax.swing.JTextField jtf_cantv;
    private javax.swing.JTextField jtf_codigo;
    private javax.swing.JTextField jtf_edadm;
    private javax.swing.JTextField jtf_edadu;
    private javax.swing.JTextField jtf_nombretor;
    private javax.swing.JTextField jtf_numeroe;
    private javax.swing.JTextField jtf_pesoc;
    private javax.swing.JTextField jtf_pesotor;
    private javax.swing.JTextField jtf_raza;
    private javax.swing.JTextField jtf_region;
    private javax.swing.JMenuItem m_eliminar;
    private javax.swing.JMenuItem m_modificar;
    private javax.swing.JPopupMenu menupop;
    private javax.swing.JPopupMenu poparbol;
    private javax.swing.JMenuItem t_eliminar;
    private javax.swing.JMenuItem t_modificar;
    // End of variables declaration//GEN-END:variables
}
